version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
      - image: circleci/mongo:latest
      environment:
        MONGO_URL: mongodb://localhost/test
        NODE_ENV: test
        
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install --save
      - run:
          name: run tests
          command: |
            npm test

workflows:
  build_test:
    jobs:
      - build
