# @format

name: Node.js CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches: [master]

jobs:
  build:
    env:
      MONGO_URL: mongodb://localhost/test
      NODE_ENV: test
      JWT_SECRECT: ${{ secrets.JWT_SECRECT }}
      KEY_ID: ${{ secrets.KEY_ID }}
      KEY_SECRET: ${{ secrets.KEYSECRET }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        mongodb-version: ["4.4"]

    steps:
      - name: git checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - run: npm i
      - run: npm test

      - name: Deploy to Railway
        uses: devtomio/action-railway@v1.1.4
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
